defaults: &defaults
  working_directory: /build
  docker:
    - image: docker:17.05.0-ce-git
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        keys:
          - v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
        paths:
          - /caches/images/
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          for image in /caches/images/*.tar
          do docker load -i $image | true
          done
    - run:
        name: Build base Docker image
        command: |
          docker build --cache-from=rust-$RUST_IMAGE -t rust-$RUST_IMAGE -f rust/src/ci/docker/$RUST_IMAGE/Dockerfile rust/src/ci/docker
          container=$(docker create --rm rust-$RUST_IMAGE /bin/bash -c 'cd /target-extractor && mkdir workdir && cd workdir && eval "$SCRIPT"')
          docker cp target-extractor $container:/target-extractor
          targets=$(docker start -a "$container")
          echo >&2 "Targets: $targets"
          echo "export TARGETS='$targets'" >> $BASH_ENV
    - run:
        name: Tag buildenv Docker image
        command: |
          source $BASH_ENV
          for target in $TARGETS
          do
              echo >&2 "Tagging target: $target"
              docker tag rust-$RUST_IMAGE dflemstr/rust-buildenv:$target
          done
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches/images
          docker save -o /caches/images/rust-$RUST_IMAGE.tar rust-$RUST_IMAGE
    - save_cache:
        key: v1-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/images
    - deploy:
        name: Push application Docker image
        command: |
          source $BASH_ENV
          if [ "${CIRCLE_BRANCH}" == "master" ]
          then
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            for target in $TARGETS
            do
              echo >&2 "Pushing target: $target"
              docker push dflemstr/rust-buildenv:$target
            done
          fi

version: 2
jobs:
  dist-various-1:
    <<: *defaults
    environment: RUST_IMAGE=dist-various-1
  dist-various-2:
    <<: *defaults
    environment: RUST_IMAGE=dist-various-2
  dist-aarch64-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-aarch64-linux
  dist-android:
    <<: *defaults
    environment: RUST_IMAGE=dist-android
  dist-arm-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-arm-linux
  dist-armhf-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-armhf-linux
  dist-armv7-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-armv7-linux
  dist-i586-gnu-i586-i686-musl:
    <<: *defaults
    environment: RUST_IMAGE=dist-i586-gnu-i586-i686-musl
  dist-i686-freebsd:
    <<: *defaults
    environment: RUST_IMAGE=dist-i686-freebsd
  dist-i686-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-i686-linux
  dist-mips-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-mips-linux
  dist-mips64-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-mips64-linux
  dist-mips64el-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-mips64el-linux
  dist-mipsel-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-mipsel-linux
  dist-powerpc-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-powerpc-linux
  dist-powerpc64-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-powerpc64-linux
  dist-powerpc64le-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-powerpc64le-linux
  dist-s390x-linux:
    <<: *defaults
    environment: RUST_IMAGE=dist-s390x-linux
  dist-x86_64-freebsd:
    <<: *defaults
    environment: RUST_IMAGE=dist-x86_64-freebsd
  dist-x86_64-musl:
    <<: *defaults
    environment: RUST_IMAGE=dist-x86_64-musl
  dist-x86_64-netbsd:
    <<: *defaults
    environment: RUST_IMAGE=dist-x86_64-netbsd

workflows:
  version: 2
  dist:
    jobs:
      - dist-aarch64-linux
      - dist-android
      - dist-armhf-linux
      - dist-arm-linux
      - dist-armv7-linux
      - dist-i586-gnu-i586-i686-musl
      - dist-i686-freebsd
      - dist-i686-linux
      - dist-mips64el-linux
      - dist-mips64-linux
      - dist-mipsel-linux
      - dist-mips-linux
      - dist-powerpc64le-linux
      - dist-powerpc64-linux
      - dist-powerpc-linux
      - dist-s390x-linux
      - dist-various-1
      - dist-various-2
      - dist-x86_64-freebsd
      - dist-x86_64-linux
      - dist-x86_64-musl
      - dist-x86_64-netbsd
