FROM japaric/i686-unknown-linux-gnu

COPY install.sh /
RUN /install.sh

RUN apt-get update && \
    apt-get install -y gcc-4.8 g++-4.8 && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.6 50 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 50 && \
    update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-4.8 100 && \
    update-alternatives --install /usr/bin/cpp cpp-bin /usr/bin/cpp-4.6 50 && \
    update-alternatives --auto g++ && \
    update-alternatives --auto gcc && \
    update-alternatives --auto cpp-bin
